### ISSUE TITLE
Laravel wrapper

### ISSUE THREAD

**Issue by APdevelopments** [checkout/checkout-php-library#101]
Hi,

Can you please help with Laravel integration? Can someone create a short tutorial how to implement this library at Laravel?

**Comment by nicolas-maalouf-cko** [comment]
Hi,

You should be able to fetch the latest version of the library using Composer in Laravel.

`composer require checkout/checkout-php-api`

**Comment by APdevelopments** [comment]
Yes, and now I got ApiHttpClientCustomException in ApiHttpClient.php line 40:

**Comment by nicolas-maalouf-cko** [comment]
Closing this issue as it has been resolved in your email exchanges with our team
