### ISSUE TITLE
Possible error of sample parameter given in Charge with Card Token

### ISSUE THREAD

**Issue by carlbinalla** [checkout/checkout-php-library#103]
I noticed that the sample parameter given in `setCardToken()` looks like a **Card Id** rather that a **Card Token**, mainly because of the missing **_tok_**.

Looking at the documentation, it seems that a **Card Id** is different from a **Card Token**. I suggest that it is changed to avoid confusion, unless the sample is really correct.

**Comment by nicolas-maalouf-cko** [comment]
Hi @carlbinalla 

Thanks for notifying us, we updated the code sample
