### ISSUE TITLE
Documentation for charging card-tokens

### ISSUE THREAD

**Issue by matt-usurp** [checkout/checkout-php-library#78]
https://github.com/checkout/checkout-php-library/wiki/Charges#creates-a-charge-with-cardtoken

At this part of the documentation there is mention of `$billingDetails` that is never used. I am unsure if I should be passing this through and if so where. At least it works without it but potentially something that needs fixing in the documentation.

**Comment by nicolas-maalouf-cko** [comment]
Hi @matt-usurp 

Please note that $billingDetails is added to $CardTokenChargePayload and is used on the payment gateway when attempting the charge
