### ISSUE TITLE
Charge Response object is missing Redirect Url

### ISSUE THREAD

**Issue by matt-usurp** [checkout/checkout-php-library#79]
https://github.com/checkout/checkout-php-library/blob/master/com/checkout/ApiServices/Charges/ResponseModels/Charge.php

When `3D Secure` is enabled the redirect url is returned in the response `json` but there is no getter that can access this information from the charge object itself.

**Comment by nicolas-maalouf-cko** [comment]
@matt-usurp 
This has been added in the latest release (v1.2.7)

You can also get the responseType in Charge responses which allows you to know whether it's a 3dCharge, attemptN3dCharge, or normal response.

**Comment by matt-usurp** [comment]
Thanks!
