### ISSUE TITLE
Composer install problem

### ISSUE THREAD

**Issue by navihtot** [checkout/checkout-php-library#90]
Hi,
I'm trying to install via composer and I get this error:

```
composer require checkout/checkout-php-api
[InvalidArgumentException]                                                                                                                                 
  Could not find package checkout/checkout-php-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 
```

 Any help would be much appreciated.

**Comment by ioan-ghisoi-cko** [comment]
@navihtot  

What php version are you using?

Also, can you please try to do:

`composer update`
`composer clearcache `

  and then 

`composer require checkout/checkout-php-api`

**Comment by navihtot** [comment]
Thanks for your reply.
And sorry my bad - project I was working on had a setting in composer which was allowing only pull from internal company repositories so no github etc.
