### ISSUE TITLE
Charge with Card Token example missing a line of code (corresponding to release v1.2.10) 

### ISSUE THREAD

**Issue by ioan-ghisoi-cko** [checkout/checkout-php-library#93]
[At this location.](https://github.com/checkout/checkout-php-library/wiki/Charges#creates-a-charge-with-cardtoken)

After the billing details are set, they are not added to the Charge.

This should be set after `$billingDetails->setXXXXX`:
`
$CardTokenChargePayload->setBillingDetails($billingDetails);`

**Comment by avish-bisbeehurry-cko** [comment]
Missing line of code added to wiki documentation
